<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>files</key>
	<dict>
		<key>AppIcon60x60@2x.png</key>
		<data>
		GzrDC/T/l0rH5OezcNE+5avc8ZE=
		</data>
		<key>AppIcon76x76@2x~ipad.png</key>
		<data>
		NdZcB1e+nRcGiSrCYoj0aHpII+U=
		</data>
		<key>Assets.car</key>
		<data>
		KxTRGMWPgd9mIsZ0i19gyip+QFk=
		</data>
		<key>Info.plist</key>
		<data>
		Kky1WhMhCZ7EwNuCnIUXxs2H7bI=
		</data>
		<key>PkgInfo</key>
		<data>
		n57qDP4tZfLD1rCS43W0B4LQjzE=
		</data>
		<key>Settings.bundle/Root.plist</key>
		<data>
		G0H8PlX5lJ8hM+WDNME1XU9wkYA=
		</data>
		<key>Settings.bundle/en.lproj/Root.strings</key>
		<dict>
			<key>hash</key>
			<data>
			vjQNKHdqtCIceSieEuXC52dr+7g=
			</data>
			<key>optional</key>
			<true/>
		</dict>
		<key>Settings.bundle/zh_Hans.lproj/Root.strings</key>
		<dict>
			<key>hash</key>
			<data>
			wVOfmaWw6MyHijFBI3ZJmS4Qh7M=
			</data>
			<key>optional</key>
			<true/>
		</dict>
		<key>SignedByEsign</key>
		<data>
		2Kh2j93606gnpedlrHVB7ZTqvWo=
		</data>
		<key>en.lproj/InfoPlist.strings</key>
		<dict>
			<key>hash</key>
			<data>
			zmV6UqBSo6r1NOz798vd5O4zTBA=
			</data>
			<key>optional</key>
			<true/>
		</dict>
		<key>en.lproj/Localizable.strings</key>
		<dict>
			<key>hash</key>
			<data>
			qqwNLjJZUAV1c5wnEiUCE5ZZjzg=
			</data>
			<key>optional</key>
			<true/>
		</dict>
		<key>es.lproj/InfoPlist.strings</key>
		<dict>
			<key>hash</key>
			<data>
			zmV6UqBSo6r1NOz798vd5O4zTBA=
			</data>
			<key>optional</key>
			<true/>
		</dict>
		<key>es.lproj/Localizable.strings</key>
		<dict>
			<key>hash</key>
			<data>
			nBNOb8M0qg6/Ra7DyIQ01iFej3c=
			</data>
			<key>optional</key>
			<true/>
		</dict>
		<key>icon.png</key>
		<data>
		RGlhxKzcHGKtQWP7zGP2E5vT/uw=
		</data>
		<key>icon@2x.png</key>
		<data>
		RGlhxKzcHGKtQWP7zGP2E5vT/uw=
		</data>
		<key>icon@3x.png</key>
		<data>
		RGlhxKzcHGKtQWP7zGP2E5vT/uw=
		</data>
		<key>openssl.framework/Headers/aes.h</key>
		<data>
		/QHXsfp5KZBtt0hpQ+PGhRB5TQE=
		</data>
		<key>openssl.framework/Headers/asn1.h</key>
		<data>
		/JULnimbzTltoXNqIFMZvE15UFw=
		</data>
		<key>openssl.framework/Headers/asn1err.h</key>
		<data>
		vClK4nFx8VUb19HBjU1cQuNfemY=
		</data>
		<key>openssl.framework/Headers/asn1t.h</key>
		<data>
		LWrSPPRO1SZ6tiCyd9G2baHBT0g=
		</data>
		<key>openssl.framework/Headers/async.h</key>
		<data>
		Du5KwAWX1O4Ld/G5CC+CgQkQU9M=
		</data>
		<key>openssl.framework/Headers/asyncerr.h</key>
		<data>
		K5Jc+TuPuL/d4mP5tAhHKE2LRmc=
		</data>
		<key>openssl.framework/Headers/bio.h</key>
		<data>
		3e8z1vvxgbXPwmeg+1bRSmgfCG8=
		</data>
		<key>openssl.framework/Headers/bioerr.h</key>
		<data>
		N0rVDI9qQwyDEWvlqW1vGQrh0RU=
		</data>
		<key>openssl.framework/Headers/blowfish.h</key>
		<data>
		BLqJpLWCl4Gl0DR4WO0luoyixMg=
		</data>
		<key>openssl.framework/Headers/bn.h</key>
		<data>
		zwKCI0fcYjm7MT9ZsUzGG4BDLTE=
		</data>
		<key>openssl.framework/Headers/bnerr.h</key>
		<data>
		ybn9OmsYdCvnSKGlXSQQJ8b+Y44=
		</data>
		<key>openssl.framework/Headers/buffer.h</key>
		<data>
		70BHajzy0JGUYwo7F+dpD0CeWrs=
		</data>
		<key>openssl.framework/Headers/buffererr.h</key>
		<data>
		PSVdu9joU+POeEegSPtAPctXWyI=
		</data>
		<key>openssl.framework/Headers/camellia.h</key>
		<data>
		R0cxfQe4VMejfw/FBnV5jlrTxS8=
		</data>
		<key>openssl.framework/Headers/cast.h</key>
		<data>
		tg9fweKyld2MF5c1iw7sEh5btDM=
		</data>
		<key>openssl.framework/Headers/cmac.h</key>
		<data>
		SsfJcPvnO3RZ7i+QyWeuyIBoFr4=
		</data>
		<key>openssl.framework/Headers/cms.h</key>
		<data>
		WhfyS38eVlM/0EjH+SRNVL1fhB0=
		</data>
		<key>openssl.framework/Headers/cmserr.h</key>
		<data>
		icv8DehBtI8fn3XrZvJ8GaK3Nm8=
		</data>
		<key>openssl.framework/Headers/comp.h</key>
		<data>
		iXVcuTWmFCf9QLEmp9sNP8JQUw0=
		</data>
		<key>openssl.framework/Headers/comperr.h</key>
		<data>
		smXqglFOEgRt0CXetpBcXnWbZYI=
		</data>
		<key>openssl.framework/Headers/conf.h</key>
		<data>
		lY422quRPGGoMtvoZu73RVfY38s=
		</data>
		<key>openssl.framework/Headers/conf_api.h</key>
		<data>
		aEkI7MCNJGZ+SJxs514uMY1oW3s=
		</data>
		<key>openssl.framework/Headers/conferr.h</key>
		<data>
		HhxJvI2jMpKEWKwpMC+m/3YD5tE=
		</data>
		<key>openssl.framework/Headers/crypto.h</key>
		<data>
		9mlWjKYcqA63rFf05YOE/OnlLlE=
		</data>
		<key>openssl.framework/Headers/cryptoerr.h</key>
		<data>
		rvUn24W+SZM/y6GTW6NG1DW8KQo=
		</data>
		<key>openssl.framework/Headers/ct.h</key>
		<data>
		cpeLfPNApLUZ414BRmIcahaW0y0=
		</data>
		<key>openssl.framework/Headers/cterr.h</key>
		<data>
		z6hnmIDS0tby0u7XWscijJOnipQ=
		</data>
		<key>openssl.framework/Headers/des.h</key>
		<data>
		znOw/0Vq2B1QWQ5QlySAEIkrdwE=
		</data>
		<key>openssl.framework/Headers/dh.h</key>
		<data>
		9zO15LRHFl5v1MTrCuS3Q2iGGu0=
		</data>
		<key>openssl.framework/Headers/dherr.h</key>
		<data>
		PTwLUzp4LhfTwc/VMpRyT9YTuRU=
		</data>
		<key>openssl.framework/Headers/dsa.h</key>
		<data>
		AEYyYVu2fy7yPpiyRyjyypHNCKI=
		</data>
		<key>openssl.framework/Headers/dsaerr.h</key>
		<data>
		jmOqsG1TSs1yTIm74Qstlz/KODg=
		</data>
		<key>openssl.framework/Headers/dtls1.h</key>
		<data>
		fDDC+ixg7o1tDB4basD847J6+Zk=
		</data>
		<key>openssl.framework/Headers/e_os2.h</key>
		<data>
		lavqS62GkOuhGihyu+WOjVd92SM=
		</data>
		<key>openssl.framework/Headers/ebcdic.h</key>
		<data>
		z5Fn9TbPaQo8zoY+Uwo/lSr9SJ8=
		</data>
		<key>openssl.framework/Headers/ec.h</key>
		<data>
		VDanIs80uH9tNKL+PSMmYL0YIu4=
		</data>
		<key>openssl.framework/Headers/ecdh.h</key>
		<data>
		iXUqwjlcXCix2i1+T/zXRV4PU18=
		</data>
		<key>openssl.framework/Headers/ecdsa.h</key>
		<data>
		iXUqwjlcXCix2i1+T/zXRV4PU18=
		</data>
		<key>openssl.framework/Headers/ecerr.h</key>
		<data>
		GyM9ZofjjCqJIe+IbO9j4p+HDZk=
		</data>
		<key>openssl.framework/Headers/engine.h</key>
		<data>
		dS4eXHBYjCoSL3nDXCYuyZR9V9c=
		</data>
		<key>openssl.framework/Headers/engineerr.h</key>
		<data>
		H6oGO47GeHqzTYa913WPlF5cZzQ=
		</data>
		<key>openssl.framework/Headers/err.h</key>
		<data>
		OZsmLZ7UryVhV7QY17J5cymnWlY=
		</data>
		<key>openssl.framework/Headers/evp.h</key>
		<data>
		Ue0l0jetFcNRP+2k4ve5l9kWsOw=
		</data>
		<key>openssl.framework/Headers/evperr.h</key>
		<data>
		YPfW2qvVYScvnOl+vKfUlzf4pvg=
		</data>
		<key>openssl.framework/Headers/hmac.h</key>
		<data>
		oNXOm72CsIiR3i2/7dzmPfXHpnk=
		</data>
		<key>openssl.framework/Headers/idea.h</key>
		<data>
		9OhfGjNERiWm+IaFZng3mj74a70=
		</data>
		<key>openssl.framework/Headers/kdf.h</key>
		<data>
		8bAA2Z5x72kQuKB9lY8B07YpOvA=
		</data>
		<key>openssl.framework/Headers/kdferr.h</key>
		<data>
		eBl7XkjAByV3fh1j+2ZSsSVdPd0=
		</data>
		<key>openssl.framework/Headers/lhash.h</key>
		<data>
		gsp3p9sYfgyLm8w777aVi7LZzaA=
		</data>
		<key>openssl.framework/Headers/md2.h</key>
		<data>
		SU5g+hFH8KXJwSElUE6qnz88XbQ=
		</data>
		<key>openssl.framework/Headers/md4.h</key>
		<data>
		NVmYVdXaFSHylpRJRh52LUqSAIY=
		</data>
		<key>openssl.framework/Headers/md5.h</key>
		<data>
		8R2dids4HGec0BuJ5RjnI0sNAqs=
		</data>
		<key>openssl.framework/Headers/mdc2.h</key>
		<data>
		ceP5kO5gOJDJGS7HrDRjpWWG2i4=
		</data>
		<key>openssl.framework/Headers/modes.h</key>
		<data>
		oykGDYKdMkpM+dh+C5148xyIG9A=
		</data>
		<key>openssl.framework/Headers/obj_mac.h</key>
		<data>
		0xczM7tqfkjs0KVU5TgD3MmB0O8=
		</data>
		<key>openssl.framework/Headers/objects.h</key>
		<data>
		1BKkzZQ86VAQYSD2wS3W+kAe8lU=
		</data>
		<key>openssl.framework/Headers/objectserr.h</key>
		<data>
		62CLZz09xeqGq4nUpt1HfuvRrbM=
		</data>
		<key>openssl.framework/Headers/ocsp.h</key>
		<data>
		/vPykCbZnxZ/oD4x73y3vCFlfAg=
		</data>
		<key>openssl.framework/Headers/ocsperr.h</key>
		<data>
		HzVTI0XxPNFGeTAYcha32Bf1qLw=
		</data>
		<key>openssl.framework/Headers/openssl.h</key>
		<data>
		BiYfZ0zrJVilXOOlvW591+Rw2xs=
		</data>
		<key>openssl.framework/Headers/opensslconf.h</key>
		<data>
		H/GpeE/IBdD04wzUSASIhcyVtiA=
		</data>
		<key>openssl.framework/Headers/opensslv.h</key>
		<data>
		s97vJrymjyoCPk8+0INGAxZyyVM=
		</data>
		<key>openssl.framework/Headers/ossl_typ.h</key>
		<data>
		/hD+IfNYoPQpFE2wIl8jHi6BRVI=
		</data>
		<key>openssl.framework/Headers/pem.h</key>
		<data>
		32ly0pNLPzdTYGECzCbGY6huGuw=
		</data>
		<key>openssl.framework/Headers/pem2.h</key>
		<data>
		t2jj9ipWiYEJZvgm7/w68FCv7xk=
		</data>
		<key>openssl.framework/Headers/pemerr.h</key>
		<data>
		LPK/t/8oy0h9S1TUlxQnvG640ps=
		</data>
		<key>openssl.framework/Headers/pkcs12.h</key>
		<data>
		Wgtt5Ajf2I0Qe0Yw/C6/da673Vs=
		</data>
		<key>openssl.framework/Headers/pkcs12err.h</key>
		<data>
		iYGY/k8EiROz+H6/d3nIzlOnXHY=
		</data>
		<key>openssl.framework/Headers/pkcs7.h</key>
		<data>
		DSVKNOqJWVpNEj9g1afFP/AAHbs=
		</data>
		<key>openssl.framework/Headers/pkcs7err.h</key>
		<data>
		vbVkdgXZDNlmUBjHsDcvjoyWNTE=
		</data>
		<key>openssl.framework/Headers/rand.h</key>
		<data>
		BUI/kpuBobNUPlXrW/OkHeq9ClM=
		</data>
		<key>openssl.framework/Headers/rand_drbg.h</key>
		<data>
		dZJZsnraib5Oxt12qSJ4bXxP3/w=
		</data>
		<key>openssl.framework/Headers/randerr.h</key>
		<data>
		/b3o6sjMLxkewJmLW7LeYF/10A0=
		</data>
		<key>openssl.framework/Headers/rc2.h</key>
		<data>
		Xzwvx1iv4W35klxWCpyRR35/Uwc=
		</data>
		<key>openssl.framework/Headers/rc4.h</key>
		<data>
		01mH39v8pvXIdzB3N/3bn0uJwVs=
		</data>
		<key>openssl.framework/Headers/rc5.h</key>
		<data>
		nVMdNFdbOheiSzNQjJ5v92LvEmI=
		</data>
		<key>openssl.framework/Headers/ripemd.h</key>
		<data>
		UUNVXGUU1UnsGpXivIzpc/ZyFQs=
		</data>
		<key>openssl.framework/Headers/rsa.h</key>
		<data>
		BXOED7wh3elZhA9q8KoFrXffhUg=
		</data>
		<key>openssl.framework/Headers/rsaerr.h</key>
		<data>
		jrv7NJXCaI3Ppho9VNnyZFn9jxQ=
		</data>
		<key>openssl.framework/Headers/safestack.h</key>
		<data>
		Cd9WYSUSt9OnXah9XHF3QevCc+E=
		</data>
		<key>openssl.framework/Headers/seed.h</key>
		<data>
		xIqmrORS9667meS1VHouBNO1FGI=
		</data>
		<key>openssl.framework/Headers/sha.h</key>
		<data>
		lu1HA4odImsyOAN6vcDKaHOxMrc=
		</data>
		<key>openssl.framework/Headers/shim.h</key>
		<data>
		4iqcfNPeL+Z/5gUHm5g5/ypWxKQ=
		</data>
		<key>openssl.framework/Headers/srp.h</key>
		<data>
		hs0FaZQgqkGx2ATJtkZLR3E7ajQ=
		</data>
		<key>openssl.framework/Headers/srtp.h</key>
		<data>
		Xiev9lzpqvNNo1eXz+UZl4RZh+0=
		</data>
		<key>openssl.framework/Headers/ssl.h</key>
		<data>
		mhalYjN/qeuEF+l6WIVquvXvjOs=
		</data>
		<key>openssl.framework/Headers/ssl2.h</key>
		<data>
		ZUBF9zzQr/EnSx9hH0JCB0ETP8s=
		</data>
		<key>openssl.framework/Headers/ssl3.h</key>
		<data>
		cA/eJmiVcOy62x5KksvM5fafytI=
		</data>
		<key>openssl.framework/Headers/sslerr.h</key>
		<data>
		4EiOgpXMaHQuyZqwDCHkMoCYXhw=
		</data>
		<key>openssl.framework/Headers/stack.h</key>
		<data>
		HlhyAUEwF7fsEBjOpYfB+ZGw2SU=
		</data>
		<key>openssl.framework/Headers/store.h</key>
		<data>
		f3f0erlSosQY7bDqrHLGzKe7YY4=
		</data>
		<key>openssl.framework/Headers/storeerr.h</key>
		<data>
		kv/pt/4V9S0com6azZDBL4S2ef4=
		</data>
		<key>openssl.framework/Headers/symhacks.h</key>
		<data>
		9immsicIban6k2s+1MF7N3ITwzE=
		</data>
		<key>openssl.framework/Headers/tls1.h</key>
		<data>
		snV9T38ogNzmGbcPr9Rn32lFHOo=
		</data>
		<key>openssl.framework/Headers/ts.h</key>
		<data>
		iWDV/jVLCzacuMrj1s833l3wAYY=
		</data>
		<key>openssl.framework/Headers/tserr.h</key>
		<data>
		PI3IsQNlWi/RwHMUbbL1VJDUvj0=
		</data>
		<key>openssl.framework/Headers/txt_db.h</key>
		<data>
		NoTeslBGWtynVU+GDhyxyzXUdTE=
		</data>
		<key>openssl.framework/Headers/ui.h</key>
		<data>
		++9liaOBXfJY40d+p4saEce2zpw=
		</data>
		<key>openssl.framework/Headers/uierr.h</key>
		<data>
		R61EyGTilaauZmnHry4jjFiN5ko=
		</data>
		<key>openssl.framework/Headers/whrlpool.h</key>
		<data>
		Uo0K/dGVqhsRUor/8CFpmWNaoHY=
		</data>
		<key>openssl.framework/Headers/x509.h</key>
		<data>
		5wWbXaF8/6/pZR0i8O64cxA2vYY=
		</data>
		<key>openssl.framework/Headers/x509_vfy.h</key>
		<data>
		+5MyYNetMS2YX3CRFqSzMEZc4TE=
		</data>
		<key>openssl.framework/Headers/x509err.h</key>
		<data>
		z4/1nUkbgTSuqRKSBA/+tS9zTD4=
		</data>
		<key>openssl.framework/Headers/x509v3.h</key>
		<data>
		YhR8NOnXe50FuvmDc73j2oiOZGo=
		</data>
		<key>openssl.framework/Headers/x509v3err.h</key>
		<data>
		X1T6LneJ+WEeudGjNgNYP08RqMU=
		</data>
		<key>openssl.framework/Info.plist</key>
		<data>
		HuSRZ4zF4B1gEGeQ9aoIQi1F19s=
		</data>
		<key>openssl.framework/Modules/module.modulemap</key>
		<data>
		bROi2EOoTr4BNb6QSpIeexBjDw8=
		</data>
		<key>openssl.framework/_CodeSignature/CodeDirectory</key>
		<data>
		jGVRksjBc0N83L/NWmQ4aEtRoY4=
		</data>
		<key>openssl.framework/_CodeSignature/CodeRequirements</key>
		<data>
		yG9iAFyeYM/um7Q1BVr/U/h28X4=
		</data>
		<key>openssl.framework/_CodeSignature/CodeRequirements-1</key>
		<data>
		hLApeoTjBs3qSUZhsJv/jPGKGKo=
		</data>
		<key>openssl.framework/_CodeSignature/CodeResources</key>
		<data>
		VTFjK1z92JwyxxiERnE36dqhleo=
		</data>
		<key>openssl.framework/_CodeSignature/CodeSignature</key>
		<data>
		hdex20uRhI4L+GIRLCCnHdvpjyc=
		</data>
		<key>openssl.framework/openssl</key>
		<data>
		mnWHm9nQZfu3MHIlZHlXkcQnUNE=
		</data>
		<key>zh-Hans.lproj/InfoPlist.strings</key>
		<dict>
			<key>hash</key>
			<data>
			zmV6UqBSo6r1NOz798vd5O4zTBA=
			</data>
			<key>optional</key>
			<true/>
		</dict>
		<key>zh-Hans.lproj/Localizable.strings</key>
		<dict>
			<key>hash</key>
			<data>
			J0nTvnUQU59qMU95G9XX0vxYfnQ=
			</data>
			<key>optional</key>
			<true/>
		</dict>
	</dict>
	<key>files2</key>
	<dict>
		<key>AppIcon60x60@2x.png</key>
		<dict>
			<key>hash</key>
		<data>
			GzrDC/T/l0rH5OezcNE+5avc8ZE=
			</data>
			<key>hash2</key>
			<data>
			/kmldk8sB8Paw5Wt1WC0YA08i4yHf3HkI8hTTh9BvW0=
			</data>
		</dict>
		<key>AppIcon76x76@2x~ipad.png</key>
		<dict>
			<key>hash</key>
			<data>
			NdZcB1e+nRcGiSrCYoj0aHpII+U=
			</data>
			<key>hash2</key>
			<data>
			Cadl7cUELY9zRagkDCl5fHSoZygR4STfUEHk/hr/Two=
			</data>
		</dict>
		<key>Assets.car</key>
		<dict>
			<key>hash</key>
			<data>
			KxTRGMWPgd9mIsZ0i19gyip+QFk=
			</data>
			<key>hash2</key>
			<data>
			EO5U6bzbpwoIFODhKTXdexBzQMa/ZJeCaELB7wHmYbQ=
			</data>
		</dict>
		<key>Settings.bundle/Root.plist</key>
		<dict>
			<key>hash</key>
			<data>
			G0H8PlX5lJ8hM+WDNME1XU9wkYA=
			</data>
			<key>hash2</key>
			<data>
			jgm+9LHcJfxnm6hG90Irgu3BoikHoTr/IxKxO/7nk0M=
			</data>
		</dict>
		<key>Settings.bundle/en.lproj/Root.strings</key>
		<dict>
			<key>hash</key>
			<data>
			vjQNKHdqtCIceSieEuXC52dr+7g=
			</data>
			<key>hash2</key>
			<data>
			Qq0p4Zvo25KYvrbFQIDiyoBp91xoVYxAWJQ71E+ilqQ=
			</data>
			<key>optional</key>
			<true/>
		</dict>
		<key>Settings.bundle/zh_Hans.lproj/Root.strings</key>
		<dict>
			<key>hash</key>
			<data>
			wVOfmaWw6MyHijFBI3ZJmS4Qh7M=
			</data>
			<key>hash2</key>
			<data>
			61luY1AJ6uB6ZCOBzWXJv+y6mLY7H4ri21sHTue1hgo=
			</data>
			<key>optional</key>
			<true/>
		</dict>
		<key>SignedByEsign</key>
		<dict>
			<key>hash</key>
			<data>
			2Kh2j93606gnpedlrHVB7ZTqvWo=
			</data>
			<key>hash2</key>
			<data>
			Bj6LsjWe74UB4viq1FOQ3dJVt3yB+9PDUQOwRGezWZI=
			</data>
		</dict>
		<key>en.lproj/InfoPlist.strings</key>
		<dict>
			<key>hash</key>
			<data>
			zmV6UqBSo6r1NOz798vd5O4zTBA=
			</data>
			<key>hash2</key>
			<data>
			kmHsztpgjvF0JW5f3HdMHm49z1M0CcG8OT1JDQHHE/E=
			</data>
			<key>optional</key>
			<true/>
		</dict>
		<key>en.lproj/Localizable.strings</key>
		<dict>
			<key>hash</key>
			<data>
			qqwNLjJZUAV1c5wnEiUCE5ZZjzg=
			</data>
			<key>hash2</key>
			<data>
			yT1953ycYZ1Y34o7Hg7SCWB0E3j6BXR41gEALZS85h0=
			</data>
			<key>optional</key>
			<true/>
		</dict>
		<key>es.lproj/InfoPlist.strings</key>
		<dict>
			<key>hash</key>
			<data>
			zmV6UqBSo6r1NOz798vd5O4zTBA=
			</data>
			<key>hash2</key>
			<data>
			kmHsztpgjvF0JW5f3HdMHm49z1M0CcG8OT1JDQHHE/E=
			</data>
			<key>optional</key>
			<true/>
		</dict>
		<key>es.lproj/Localizable.strings</key>
		<dict>
			<key>hash</key>
			<data>
			nBNOb8M0qg6/Ra7DyIQ01iFej3c=
			</data>
			<key>hash2</key>
			<data>
			JoLaNnZIRD50StXvRa5ffhbZeaHgpLMmBIShlA7+Ib8=
			</data>
			<key>optional</key>
			<true/>
		</dict>
		<key>icon.png</key>
		<dict>
			<key>hash</key>
			<data>
			RGlhxKzcHGKtQWP7zGP2E5vT/uw=
			</data>
			<key>hash2</key>
			<data>
			fPUJo6buA5ux5t/JDiEw+yVsJW5aqUqUIOeqHGljfQo=
			</data>
		</dict>
		<key>icon@2x.png</key>
		<dict>
			<key>hash</key>
			<data>
			RGlhxKzcHGKtQWP7zGP2E5vT/uw=
			</data>
			<key>hash2</key>
			<data>
			fPUJo6buA5ux5t/JDiEw+yVsJW5aqUqUIOeqHGljfQo=
			</data>
		</dict>
		<key>icon@3x.png</key>
		<dict>
			<key>hash</key>
			<data>
			RGlhxKzcHGKtQWP7zGP2E5vT/uw=
			</data>
			<key>hash2</key>
			<data>
			fPUJo6buA5ux5t/JDiEw+yVsJW5aqUqUIOeqHGljfQo=
			</data>
		</dict>
		<key>openssl.framework/Headers/aes.h</key>
		<dict>
			<key>hash</key>
			<data>
			/QHXsfp5KZBtt0hpQ+PGhRB5TQE=
			</data>
			<key>hash2</key>
			<data>
			9ron6H2X6lePAVQKj4S36rBdQsF4utznEtDMZo2KmYE=
			</data>
		</dict>
		<key>openssl.framework/Headers/asn1.h</key>
		<dict>
			<key>hash</key>
			<data>
			/JULnimbzTltoXNqIFMZvE15UFw=
			</data>
			<key>hash2</key>
			<data>
			hRMTsRdrqj1olqru6+9WIW69043Nq7ObPso2tmRTUrw=
			</data>
		</dict>
		<key>openssl.framework/Headers/asn1err.h</key>
		<dict>
			<key>hash</key>
			<data>
			vClK4nFx8VUb19HBjU1cQuNfemY=
			</data>
			<key>hash2</key>
			<data>
			uJsWIW3dNfAo9b/T/g208urWyUFed0m3EVsDk7Qn7y8=
			</data>
		</dict>
		<key>openssl.framework/Headers/asn1t.h</key>
		<dict>
			<key>hash</key>
			<data>
			LWrSPPRO1SZ6tiCyd9G2baHBT0g=
			</data>
			<key>hash2</key>
			<data>
			JwL1aTAiSLgijkkxd88KRp8Sfxzlx2vGhLyQ+9/EV0M=
			</data>
		</dict>
		<key>openssl.framework/Headers/async.h</key>
		<dict>
			<key>hash</key>
			<data>
			Du5KwAWX1O4Ld/G5CC+CgQkQU9M=
			</data>
			<key>hash2</key>
			<data>
			75bHFsrDk/LNbaMErwKRVezZ8CGGnNWkw0Hr3ySQNrw=
			</data>
		</dict>
		<key>openssl.framework/Headers/asyncerr.h</key>
		<dict>
			<key>hash</key>
			<data>
			K5Jc+TuPuL/d4mP5tAhHKE2LRmc=
			</data>
			<key>hash2</key>
			<data>
			ysycqVGqUj0+1rnfI2YCJjOSWmcp0wzRNKBdL